version: '3.8' # Versão recomendada do Docker Compose

services:
  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger # Define um nome fixo para o contêiner
    restart: always # Garante que o contêiner será reiniciado se parar

    environment:
      - COLLECTOR_ZIPKIN_HOST_PORT=:9411
      - COLLECTOR_OTLP_ENABLED=true

    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "14268:14268"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"

    networks:
      - default_network # Garante que ele estará na mesma rede que outros serviços, se você tiver

networks:
  default_network:
    # driver: bridge # Opcional, o bridge é o padrão